[versions]
agp = "8.13.0"
kotlin = "2.2.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
ksp = "2.2.10-2.0.2"

retrofit = "3.0.0"
gson-converter= "3.0.0"
okHttp = "5.3.0"
interceptor="5.3.0"

hilt = "2.57.2"
hilt-android = "2.57.2"
navigation-compose = "1.3.0"

coil = "2.4.0"

corutine-test = "1.7.3"
mockk-test = "1.13.7"
junit-test = "4.13.2"
turbine-test = "1.0.0"
compose-test = "1.6.0"
android-test = "1.5.2"
android-ext-junit = "1.1.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
gson = { group = "com.squareup.retrofit2", name="converter-gson", version.ref = "gson-converter"}
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref="okHttp"}
interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref="interceptor"}
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref ="hilt-android"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref="navigation-compose"}
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref="coil"}
hilt-android-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref="hilt"}

coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref="corutine-test"}
mockk-test = { group = "io.mockk", name= "mockk", version.ref = "mockk-test"}
turbine-test = { group = "app.cash.turbine", name="turbine", version.ref = "turbine-test"}
androidx-compose = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-test" }
androidx-ui-compose = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "corutine-test"}
android-test = { group = "androidx.test", name = "runner", version.ref = "android-test"}
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "android-ext-junit"}





[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref ="hilt"}


